### ISSUE TITLE
Clicking on the number not launching macro grid

### ISSUE THREAD

**Issue by Arbitrary1079** [xaukael/macro-grid#5]
I am no longer able to activate the macro grid. The module is installed and activate, but when I click on the number to the right of the macro bar nothing happens. When I tick the "Display on Startup" option in settings, the macro grid will display when I load my world but the regular macro bar disappears and I'm unable to see and edit my players' macro bars. 

Foundery v. 11, build 315
Game System: Warhammer Fantasy Role Play v. 7.24
Macro Grid v. 2.0.1

**Comment by xaukael** [comment]
You now open the macro grid from the Players' context menu. This includes
opening other players' bars to allow you to see many at once, which I
thought an improvement. I may add the obscure clicking the number thing.
The macro grid hides the normal hotbar because I thought the normal one
redundant while the grid is up. Maybe I am misunderstanding. Why do you
still want it there?

**Comment by Arbitrary1079** [comment]
In the old version, I could edit players' micro bars by clicking on the number in the macro bar and switching the user. In the current version, I can only get the macro context menu for players when they are logged in. Unless I'm missing something, I'm no longer able to use macro grid to manage player macros between sessions.

**Comment by xaukael** [comment]
expand players to see users that are offline

**Comment by Arbitrary1079** [comment]
😬   Apologies for my poor perception checks!
